print("Hello World")
a=input("students in the class 1: ")
d=int(a)
t1=(d//2)+(d%2)
b=input("students in the class 2: ")
o=int(b)
t2=(o//2)+(o%2)
c=input("students in the class 3: ")
k=int(c)
t3=(k//2)+(k%2)
print("table in the class", (t1)+(t2)+(t3))