print ("Hello world!")
s = ("The Evaporative Air Cooler should not be used in enclosed spaces. It must be kept level and there must be water in the water tank. Doors and windows should be opened to allow free air flow. The Evaporative Air Cooler works best when placed near an open window, so that outside air is drawn into the Evaporative Air Cooler, circulates in the room, then exits via the door.")
print (s[2:3])
print (s[-2:-1])
print (s[:5])
print (s[:-3])
print (s[::2])
print (s[1::2])
print (s[:: -1])
print (s[:: -2])
print (len(s))
